applicationName: development

backend:
  replicas: 1
  image: hasnainzaib/why
  service:
    type: ClusterIP
    port: 9080

frontend:
  image: hasnainzaib/abc
  env:
  - name: BACKEND_URL
    value: development-backend:9080 
  replicas: 1
  service:
    nodePort: 32001